#!/bin/bash
#
# requires charmbracelet/skate

skate set bear@kaomoji "ʕ •ᴥ•ʔ"
skate set cat1@kaomoji "(=^･ω･^=)"
skate set cat2@kaomoji "（Φ ω Φ）"
skate set cat3@kaomoji "=^._.^="
skate set dog1@kaomoji "▼・ᴥ・▼"
skate set dog2@kaomoji "૮ ・ﻌ・ა"
skate set bat1@kaomoji "⎛⎝(ʘ ⱅ ʘ)⎠⎞"
skate set bat2@kaomoji "(㇏(♡ ᢍ ♡)ノ)blood…"
skate set bunny1@kaomoji "₍ᐢ･ × ･ᐢ₎"
skate set bird1@kaomoji "(￣Θ￣)"
skate set bird2@kaomoji "(･θ･)"
skate set fish1@kaomoji "(°)#))<<"
skate set frog1@kaomoji "₍°=  ̮ =°₎"
skate set mouse1@kaomoji "ᘛ⁐̤ᕐᐷ"
skate set pig1@kaomoji "(´・(oo)・｀)"
skate set angel1@kaomoji "ଘ( ˊωˋ )ଓ"
skate set angel2@kaomoji "ᜊ( ‘ ⩊ ‘𖦹)ᜊ"
skate set fairy1@kaomoji "ଘ(∩^o^)⊃━☆゜"
skate set fairy2@kaomoji "ଘ( ･ω･)_/ﾟ･:*:･｡☆"
skate set rilakkuma1@kaomoji "•(ㅅ)•"
skate set hellokitty1@kaomoji "ﾐ・◦・ﾐ"
skate set miffy1@kaomoji "⋆ ˚｡⋆₍ᐢ. ༝ .ᐢ₎⋆ ˚｡⋆"
skate set spiderman1@kaomoji "(ᕒ◺⁞⁞◿ᓬ)"
skate set batman1@kaomoji "ᐞ⊳៴⊲ᐞ"
skate set batman2@kaomoji "(◣_◢)"
skate set happy1@kaomoji "(≧▽≦)/"
skate set happy2@kaomoji "(°▽°)/"
skate set greeting1@kaomoji "(*・ω・)ﾉ"
skate set greeting2@kaomoji "(*・ω・)ﾉ"
skate set happy3@kaomoji "(^‿^)"
skate set happy4@kaomoji "(￣ε￣＠)"
